name: Deploy to VPS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e  # ArrÃªte le script en cas d'erreur

            echo "ğŸ” VÃ©rification du dossier /opt/streamcoin..."
            if [ ! -d "/opt/streamcoin" ]; then
              echo "ğŸ“¥ Clonage du dÃ©pÃ´t..."
              git clone https://github.com/fabricefo/streamcoin.git /opt/streamcoin
            else
              echo "ğŸ”„ Mise Ã  jour du dÃ©pÃ´t..."
              cd /opt/streamcoin
              git pull origin main
            fi

            cd /opt/streamcoin

            echo "ğŸ“ CrÃ©ation du fichier .env..."
            cat <<EOF > .env
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_PORT=${{ secrets.DB_PORT }}
            EOF

            echo "ğŸ“¦ Pull des derniÃ¨res images Docker..."
            docker pull ffourel/streamlit_app:latest
            docker pull ffourel/fastapi_app:latest

            echo "ğŸ›‘ ArrÃªt des containers existants..."
            docker compose down

            echo "ğŸš€ Lancement des containers mis Ã  jour..."
            docker compose up -d --build

            echo "âœ… DÃ©ploiement terminÃ© avec succÃ¨s."
