name: Build, Push Docker Images and Deploy to VPS

on:
  workflow_dispatch:

jobs:
  build_and_push_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Create .env file from secrets
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image for Streamlit app
        uses: docker/build-push-action@v2
        with:
          context: ./streamlit
          push: true 
          file: ./streamlit/Dockerfile
          tags: ffourel/streamlit_app:latest

      - name: Build and push Docker image for FastAPI app
        uses: docker/build-push-action@v2
        with:
          context: ./fastapi_app
          push: true 
          file: ./fastapi_app/Dockerfile
          tags: ffourel/fastapi_app:latest
          
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e  # ArrÃªte le script en cas d'erreur

            echo "ğŸ” VÃ©rification du dossier /opt/streamcoin..."
            if [ ! -d "/opt/streamcoin" ]; then
              echo "ğŸ“¥ Clonage du dÃ©pÃ´t..."
              git clone https://github.com/fabricefo/streamcoin.git /opt/streamcoin
            else
              echo "ğŸ”„ Mise Ã  jour du dÃ©pÃ´t..."
              cd /opt/streamcoin
              git pull origin main
            fi

            cd /opt/streamcoin

            echo "ğŸ“¦ Pull des derniÃ¨res images Docker..."
            docker pull ffourel/streamlit_app:latest
            docker pull ffourel/fastapi_app:latest

            echo "ğŸ›‘ ArrÃªt des containers existants..."
            docker compose down

            echo "ğŸš€ Lancement des containers mis Ã  jour..."
            docker compose up -d --build

            echo "âœ… DÃ©ploiement terminÃ© avec succÃ¨s."